In [1]:
import numpy as np
import numpy.random as rand

In [49]:
S = np.array([
    [1, 0.5, 0],
    [0.5, 1, 0],  
    [0, 0, 1]])

In [50]:
L = np.linalg.cholesky(S)

In [51]:
L.dot(L.T)

array([[1. , 0.5, 0. ],
       [0.5, 1. , 0. ],
       [0. , 0. , 1. ]])

In [52]:
L

array([[1.       , 0.       , 0.       ],
       [0.5      , 0.8660254, 0.       ],
       [0.       , 0.       , 1.       ]])

In [53]:
N = 100000

In [54]:
X = rand.normal(loc=0, scale=1, size = N * 3).reshape(N,3)
np.round(np.cov(X.T), 2) 

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

In [57]:
X = rand.normal(loc=0, scale=1, size = N * 3).reshape(N,3)
Y = L.dot(X.T)
Y = Y.T
np.round(np.cov(Y.T), 2) 

array([[ 1.  ,  0.51, -0.  ],
       [ 0.51,  1.01, -0.  ],
       [-0.  , -0.  ,  0.99]])

In [58]:
x, y, z = Y[:,0], Y[:,1], Y[:,2]
r = x**2 + y**2 + z**2 
ftr = (1/r)**0.5
p = len(ftr)

Y = np.array([Y[idx,:] * ftr[idx] for idx in range(p)])
Y

array([[-0.0946161 ,  0.13239726,  0.98667054],
       [ 0.92623594,  0.36706812,  0.08572029],
       [ 0.25536964,  0.83845478,  0.48143528],
       ...,
       [ 0.11839084,  0.81541807,  0.56663655],
       [ 0.71676897,  0.35045445,  0.60284652],
       [ 0.94082662,  0.31801399, -0.11709987]])

In [61]:
np.round(np.cov(Y.T), 2)

array([[0.33, 0.11, 0.  ],
       [0.11, 0.33, 0.  ],
       [0.  , 0.  , 0.34]])

In [59]:
np.mean(Y, axis = 0)

array([-8.33104548e-06, -4.42553646e-04, -2.65210106e-04])

In [60]:
np.var(Y, axis = 0)

array([0.32817331, 0.32944206, 0.34238437])

In [34]:
rand.seed(123)
N = 10000
#X = rand.uniform(low=-1, high=1, size = N * 3).reshape(N,3)

X = rand.normal(loc=0, scale=1, size = N * 3).reshape(N,3)

x, y, z = X[:,0], X[:,1], X[:,2]
r = x**2 + y**2 + z**2 
#idx = r < 1

#r = r[idx]
#X = X[idx,:]

ftr = (1/r)**0.5
p = len(ftr)

X = np.array([X[idx,:] * ftr[idx] for idx in range(p)])
X

array([[-0.72321256,  0.6643998 ,  0.18851127],
       [-0.65239086, -0.25059738,  0.71525319],
       [-0.87591864, -0.15481756,  0.45694427],
       ...,
       [ 0.43254994,  0.45661756, -0.77743228],
       [-0.10576127, -0.95208351,  0.28696959],
       [-0.55267261, -0.22869312,  0.80140654]])

In [35]:
np.mean(X, axis = 0)

array([ 0.0114306 ,  0.0031302 , -0.00445224])

In [36]:
np.var(X, axis = 0)

array([0.33123144, 0.33083536, 0.33777292])